/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.individual.java;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Victor Garcia
 */
public class Gerenciador extends javax.swing.JFrame {

    /**
     * Creates new form Gerenciador
     */
    Random gerador = new Random();

    Integer percCPU;
    Integer percRAM;
    Integer percDisco;

    Integer somaCPU = 0;
    Integer somaRAM = 0;
    Integer somaDisco = 0;

    Integer maxCPU = 0;
    Integer minCPU = 100;
    Integer maxRAM = 0;
    Integer minRAM = 100;
    Integer maxDisco = 0;
    Integer minDisco = 100;

    Integer contador = 0;

    public Gerenciador() {
        initComponents();
        this.getContentPane().setBackground(new Color(60, 63, 65));
        UIManager.put("nimbusOrange", new Color(65, 105, 225));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMinCPU2 = new javax.swing.JLabel();
        lblMaxCPU2 = new javax.swing.JLabel();
        lblMediaCPU2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        barCPU2 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barCPU = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMinCPU = new javax.swing.JLabel();
        lblMaxCPU = new javax.swing.JLabel();
        lblMediaCPU = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        barRAM = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        lblMinRAM = new javax.swing.JLabel();
        lblMaxRAM = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMediaRAM = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        barDisco = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();
        lblMinDisco = new javax.swing.JLabel();
        lblMaxDisco = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblMediaDisco = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlertaCPU = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlertaRAM = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAlertaDisco = new javax.swing.JTextArea();

        lblMinCPU2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMinCPU2.setText("0%");

        lblMaxCPU2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaxCPU2.setText("0%");

        lblMediaCPU2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMediaCPU2.setText("0%");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("CPU");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Mínima");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Máxima");

        barCPU2.setStringPainted(true);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Média");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(187, 187, 187));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciador");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPU");

        barCPU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        barCPU.setStringPainted(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 205, 205));
        jLabel3.setText("Mínima");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(222, 205, 205));
        jLabel4.setText("Máxima");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(222, 205, 205));
        jLabel5.setText("Média");

        lblMinCPU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMinCPU.setForeground(new java.awt.Color(255, 255, 255));
        lblMinCPU.setText("0%");

        lblMaxCPU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaxCPU.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxCPU.setText("0%");

        lblMediaCPU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMediaCPU.setForeground(new java.awt.Color(255, 255, 255));
        lblMediaCPU.setText("0%");

        jButton1.setBackground(new java.awt.Color(167, 167, 167));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Realizar Leitura dos Dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RAM");

        barRAM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        barRAM.setStringPainted(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(222, 205, 205));
        jLabel7.setText("Mínima");

        lblMinRAM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMinRAM.setForeground(new java.awt.Color(255, 255, 255));
        lblMinRAM.setText("0%");

        lblMaxRAM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaxRAM.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxRAM.setText("0%");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(222, 205, 205));
        jLabel8.setText("Máxima");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(222, 205, 205));
        jLabel9.setText("Média");

        lblMediaRAM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMediaRAM.setForeground(new java.awt.Color(255, 255, 255));
        lblMediaRAM.setText("0%");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Disco");

        barDisco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        barDisco.setStringPainted(true);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(222, 205, 205));
        jLabel15.setText("Mínima");

        lblMinDisco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMinDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblMinDisco.setText("0%");

        lblMaxDisco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaxDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxDisco.setText("0%");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(222, 205, 205));
        jLabel16.setText("Máxima");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(222, 205, 205));
        jLabel17.setText("Média");

        lblMediaDisco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMediaDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblMediaDisco.setText("0%");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(222, 205, 205));
        jLabel18.setText("Alerta (%)");

        txtAlertaCPU.setBackground(new java.awt.Color(167, 167, 167));
        txtAlertaCPU.setColumns(1);
        txtAlertaCPU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAlertaCPU.setForeground(new java.awt.Color(0, 0, 0));
        txtAlertaCPU.setRows(1);
        jScrollPane2.setViewportView(txtAlertaCPU);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(222, 205, 205));
        jLabel19.setText("Alerta (%)");

        txtAlertaRAM.setBackground(new java.awt.Color(167, 167, 167));
        txtAlertaRAM.setColumns(1);
        txtAlertaRAM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAlertaRAM.setForeground(new java.awt.Color(0, 0, 0));
        txtAlertaRAM.setRows(1);
        jScrollPane3.setViewportView(txtAlertaRAM);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(222, 205, 205));
        jLabel20.setText("Alerta (%)");

        txtAlertaDisco.setBackground(new java.awt.Color(167, 167, 167));
        txtAlertaDisco.setColumns(1);
        txtAlertaDisco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAlertaDisco.setForeground(new java.awt.Color(0, 0, 0));
        txtAlertaDisco.setRows(1);
        jScrollPane4.setViewportView(txtAlertaDisco);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(barRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4)
                                .addComponent(barCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMinCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMaxCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMediaCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMinRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMaxRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMediaRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMinDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMaxDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMediaDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinCPU)
                            .addComponent(lblMaxCPU)
                            .addComponent(lblMediaCPU))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(barRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinRAM)
                            .addComponent(lblMaxRAM)
                            .addComponent(lblMediaRAM))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMinDisco)
                                    .addComponent(lblMaxDisco)
                                    .addComponent(lblMediaDisco)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        percCPU = gerador.nextInt(101);
        percRAM = gerador.nextInt(101);
        percDisco = gerador.nextInt(101);

        if (percCPU > maxCPU) {
            maxCPU = percCPU;
            lblMaxCPU.setText(maxCPU + "%");
        }

        if (percCPU < minCPU) {
            minCPU = percCPU;
            lblMinCPU.setText(minCPU + "%");
        }

        if (percRAM > maxRAM) {
            maxRAM = percRAM;
            lblMaxRAM.setText(maxRAM + "%");
        }

        if (percRAM < minRAM) {
            minRAM = percRAM;
            lblMinRAM.setText(minRAM + "%");
        }

        if (percDisco > maxDisco) {
            maxDisco = percDisco;
            lblMaxDisco.setText(maxDisco + "%");
        }

        if (percDisco < minDisco) {
            minDisco = percDisco;
            lblMinDisco.setText(minDisco + "%");
        }

        barCPU.setValue(percCPU);
        barRAM.setValue(percRAM);
        barDisco.setValue(percDisco);

        contador++;

        somaCPU += percCPU;
        somaRAM += percRAM;
        somaDisco += percDisco;

        lblMediaCPU.setText((somaCPU / contador) + "%");
        lblMediaRAM.setText((somaRAM / contador) + "%");
        lblMediaDisco.setText((somaDisco / contador) + "%");

        Integer alertaCPU;
        Integer alertaRAM;
        Integer alertaDisco;

        if (txtAlertaCPU.getText().equals("")) {
            alertaCPU = 101;
        } else {
            alertaCPU = Integer.valueOf(txtAlertaCPU.getText());
        }

        if (txtAlertaRAM.getText().equals("")) {
            alertaRAM = 101;
        } else {
            alertaRAM = Integer.valueOf(txtAlertaRAM.getText());
        }

        if (txtAlertaDisco.getText().equals("")) {
            alertaDisco = 101;
        } else {
            alertaDisco = Integer.valueOf(txtAlertaDisco.getText());

        }

        if (percCPU >= alertaCPU) {
            JOptionPane.showMessageDialog(null, "ALERTA!!!\n\nA CPU ULTRAPASSOU SEU LIMITE INDICADO");
        }

        if (percRAM >= alertaRAM) {
            JOptionPane.showMessageDialog(null, "ALERTA!!!\n\nA RAM ULTRAPASSOU SEU LIMITE INDICADO");
        }
        
        if (percDisco >= alertaDisco) {
            JOptionPane.showMessageDialog(null, "ALERTA!!!\n\nO DISCO ULTRAPASSOU SEU LIMITE INDICADO");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerenciador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barCPU;
    private javax.swing.JProgressBar barCPU2;
    private javax.swing.JProgressBar barDisco;
    private javax.swing.JProgressBar barRAM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblMaxCPU;
    private javax.swing.JLabel lblMaxCPU2;
    private javax.swing.JLabel lblMaxDisco;
    private javax.swing.JLabel lblMaxRAM;
    private javax.swing.JLabel lblMediaCPU;
    private javax.swing.JLabel lblMediaCPU2;
    private javax.swing.JLabel lblMediaDisco;
    private javax.swing.JLabel lblMediaRAM;
    private javax.swing.JLabel lblMinCPU;
    private javax.swing.JLabel lblMinCPU2;
    private javax.swing.JLabel lblMinDisco;
    private javax.swing.JLabel lblMinRAM;
    private javax.swing.JTextArea txtAlertaCPU;
    private javax.swing.JTextArea txtAlertaDisco;
    private javax.swing.JTextArea txtAlertaRAM;
    // End of variables declaration//GEN-END:variables
}
